/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.unidad2;

/**
 *
 * @author tapia
 */
public class GestionPersona extends javax.swing.JFrame {
    
    Persona personaGUI = new Persona();
        
    /**
     * Creates new form GestionPersona
     */
    public GestionPersona() {
        initComponents();
    }
    
    public void limpiarInterfaz(){
        txtNombre.setText("");
        txtApellido.setText("");
        txtCedula.setText("");
        btnGEstadoCivil.clearSelection();
        cmbPasaTiempos.setSelectedIndex(0);
        cbxAmbato.setSelected(false);
        cbxCuenca.setSelected(false);
        cbxGuayaquil.setSelected(false);
        cbxManta.setSelected(false);
        cbxQuito.setSelected(false);
    }
    
    public void estadoCivil(){
        if(rbtnCasado.isSelected()){
            personaGUI.setEstadoCivil(rbtnCasado.getText());
        }
        if(rbtnDivorciado.isSelected()){
            personaGUI.setEstadoCivil(rbtnDivorciado.getText());
        }
        if(rbtnUnioHecho.isSelected()){
            personaGUI.setEstadoCivil(rbtnUnioHecho.getText());
        }
        if(rbtnViudo.isSelected()){
            personaGUI.setEstadoCivil(rbtnViudo.getText());
        }
        if(rbtnSoltero.isSelected()){
            personaGUI.setEstadoCivil(rbtnSoltero.getText());
        }
    }
    
    public void ciudadesQueConoce(){
        if(cbxAmbato.isSelected()){
            personaGUI.anadirCiudades(cbxAmbato.getText());
        }
        if(cbxQuito.isSelected()){
            personaGUI.anadirCiudades(cbxQuito.getText());
        }
        if(cbxGuayaquil.isSelected()){
            personaGUI.anadirCiudades(cbxGuayaquil.getText());
        }
        if(cbxManta.isSelected()){
            personaGUI.anadirCiudades(cbxManta.getText());
        }
        if(cbxCuenca.isSelected()){
            personaGUI.anadirCiudades(cbxCuenca.getText());
        }
    }
    
    /*public void imprimirCiudadesQueConoces(){
        
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGEstadoCivil = new javax.swing.ButtonGroup();
        btnGuardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmbPasaTiempos = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        rbtnCasado = new javax.swing.JRadioButton();
        rbtnSoltero = new javax.swing.JRadioButton();
        rbtnDivorciado = new javax.swing.JRadioButton();
        rbtnViudo = new javax.swing.JRadioButton();
        rbtnUnioHecho = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        cbxCuenca = new javax.swing.JCheckBox();
        cbxGuayaquil = new javax.swing.JCheckBox();
        cbxQuito = new javax.swing.JCheckBox();
        cbxAmbato = new javax.swing.JCheckBox();
        cbxManta = new javax.swing.JCheckBox();
        lblEstadoCivil = new java.awt.Label();
        lblPasaTiempo = new java.awt.Label();
        lblResumen = new java.awt.Label();
        lblCiudades = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaResumen = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmbPasaTiempos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leer", "Escribir ", "Cantar", "Bailar", "Dibujar" }));
        cmbPasaTiempos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPasaTiemposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(cmbPasaTiempos, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbPasaTiempos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblNombre.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblCedula.setText("Cedula");

        lblApellido.setText("Apellido");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCedula)
                    .addComponent(lblNombre))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtCedula))
                .addGap(97, 97, 97)
                .addComponent(lblApellido)
                .addGap(69, 69, 69)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnGEstadoCivil.add(rbtnCasado);
        rbtnCasado.setText("Casado/a");
        rbtnCasado.setInheritsPopupMenu(true);
        rbtnCasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCasadoActionPerformed(evt);
            }
        });

        btnGEstadoCivil.add(rbtnSoltero);
        rbtnSoltero.setText("Soltero/a");

        btnGEstadoCivil.add(rbtnDivorciado);
        rbtnDivorciado.setText("Divorciado/a");

        btnGEstadoCivil.add(rbtnViudo);
        rbtnViudo.setText("Viudo/a");

        btnGEstadoCivil.add(rbtnUnioHecho);
        rbtnUnioHecho.setText("Union de Hecho");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnCasado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbtnSoltero, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnViudo)
                            .addComponent(rbtnDivorciado)
                            .addComponent(rbtnUnioHecho))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(rbtnCasado)
                .addGap(18, 18, 18)
                .addComponent(rbtnSoltero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(rbtnDivorciado)
                .addGap(15, 15, 15)
                .addComponent(rbtnViudo)
                .addGap(18, 18, 18)
                .addComponent(rbtnUnioHecho)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbxCuenca.setText("Cuenca");

        cbxGuayaquil.setText("Guayaquil");

        cbxQuito.setText("Quito");

        cbxAmbato.setText("Ambato");
        cbxAmbato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAmbatoActionPerformed(evt);
            }
        });

        cbxManta.setText("Manta");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxCuenca)
                    .addComponent(cbxAmbato)
                    .addComponent(cbxManta)
                    .addComponent(cbxQuito)
                    .addComponent(cbxGuayaquil))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(cbxCuenca)
                .addGap(18, 18, 18)
                .addComponent(cbxGuayaquil)
                .addGap(18, 18, 18)
                .addComponent(cbxQuito)
                .addGap(14, 14, 14)
                .addComponent(cbxAmbato)
                .addGap(18, 18, 18)
                .addComponent(cbxManta)
                .addGap(16, 16, 16))
        );

        lblEstadoCivil.setFont(new java.awt.Font("Cambria Math", 3, 14)); // NOI18N
        lblEstadoCivil.setText("Estado Civil");

        lblPasaTiempo.setFont(new java.awt.Font("Cambria Math", 3, 14)); // NOI18N
        lblPasaTiempo.setText("Pasa TIempo");

        lblResumen.setFont(new java.awt.Font("Cambria Math", 3, 14)); // NOI18N
        lblResumen.setText("Resumen");

        lblCiudades.setFont(new java.awt.Font("Cambria Math", 3, 14)); // NOI18N
        lblCiudades.setText("Ciudades que conoce");

        txtaResumen.setEditable(false);
        txtaResumen.setColumns(20);
        txtaResumen.setRows(5);
        jScrollPane1.setViewportView(txtaResumen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(lblEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(223, 223, 223)
                            .addComponent(lblCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(187, 187, 187)
                            .addComponent(lblPasaTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(273, 273, 273)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(lblResumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(103, 103, 103)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasaTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblResumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxAmbatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAmbatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAmbatoActionPerformed

    private void rbtnCasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCasadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCasadoActionPerformed

    private void cmbPasaTiemposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPasaTiemposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPasaTiemposActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        personaGUI.setNombre(txtNombre.getText());
        personaGUI.setApellido(txtApellido.getText());
        personaGUI.setCedula(txtCedula.getText());
        personaGUI.setPasaTiempoFavorito(String.valueOf(cmbPasaTiempos.getSelectedItem()));
        personaGUI.determinarProvincia();
        estadoCivil();
        ciudadesQueConoce();
        txtaResumen.setText(personaGUI.toString());
        limpiarInterfaz();
        personaGUI.setCiudadesQueConoce("");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGEstadoCivil;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox cbxAmbato;
    private javax.swing.JCheckBox cbxCuenca;
    private javax.swing.JCheckBox cbxGuayaquil;
    private javax.swing.JCheckBox cbxManta;
    private javax.swing.JCheckBox cbxQuito;
    private javax.swing.JComboBox<String> cmbPasaTiempos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCedula;
    private java.awt.Label lblCiudades;
    private java.awt.Label lblEstadoCivil;
    private javax.swing.JLabel lblNombre;
    private java.awt.Label lblPasaTiempo;
    private java.awt.Label lblResumen;
    private javax.swing.JRadioButton rbtnCasado;
    private javax.swing.JRadioButton rbtnDivorciado;
    private javax.swing.JRadioButton rbtnSoltero;
    private javax.swing.JRadioButton rbtnUnioHecho;
    private javax.swing.JRadioButton rbtnViudo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtaResumen;
    // End of variables declaration//GEN-END:variables
}
