/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.cap1.ej2;

import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author tapia
 */
public class GestionRaton extends javax.swing.JFrame {

    Raton raton1 = new Raton();

    /**
     * Creates new form GestionRaton
     */
    public GestionRaton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCrecerNDias = new javax.swing.JButton();
        btnCrecerUnDia = new javax.swing.JButton();
        lblTasaCrecimiento = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblDias = new javax.swing.JLabel();
        txtTasaCrecimiento = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtDias = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre.setText("Nombre");

        lblEdad.setText("Edad");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCrecerNDias.setText("Crecer n Dias");
        btnCrecerNDias.setEnabled(false);
        btnCrecerNDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrecerNDiasActionPerformed(evt);
            }
        });

        btnCrecerUnDia.setText("Crecer 1 dia");
        btnCrecerUnDia.setEnabled(false);
        btnCrecerUnDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrecerUnDiaActionPerformed(evt);
            }
        });

        lblTasaCrecimiento.setText("Tasa de Crecimiento");

        lblPeso.setText("Peso");
        lblPeso.setEnabled(false);

        lblDias.setText("Dias");
        lblDias.setEnabled(false);

        txtPeso.setEnabled(false);

        txtDias.setEnabled(false);
        txtDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("GUI RATON");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEdad)
                    .addComponent(lblNombre)
                    .addComponent(lblTasaCrecimiento)
                    .addComponent(lblPeso)
                    .addComponent(lblDias)
                    .addComponent(btnGuardar))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(txtEdad)
                        .addComponent(txtTasaCrecimiento)
                        .addComponent(txtPeso)
                        .addComponent(txtDias))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrecerUnDia)
                        .addGap(47, 47, 47)
                        .addComponent(btnCrecerNDias)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTasaCrecimiento)
                    .addComponent(txtTasaCrecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDias)
                    .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCrecerUnDia)
                    .addComponent(btnCrecerNDias))
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        btnCrecerNDias.setEnabled(true);
        btnCrecerUnDia.setEnabled(true);
        lblPeso.setEnabled(true);
        txtPeso.setEnabled(true);
        lblDias.setEnabled(true);
        txtDias.setEnabled(true);
        raton1.setNombre(txtNombre.getText());
        raton1.setEdad(Integer.parseInt(txtEdad.getText()));
        raton1.setTasaCrecimientoPorcentual(Double.parseDouble(txtTasaCrecimiento.getText()));
        JOptionPane.showMessageDialog(rootPane, raton1.toString());
        txtPeso.setText(String.format("%.2f", raton1.getPeso()));
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCrecerUnDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrecerUnDiaActionPerformed
        // TODO add your handling code here:
        raton1.crecer();
        txtPeso.setText(String.format("%.2f", raton1.getPeso()));
        txtEdad.setText(String.valueOf(raton1.getEdad()));
    }//GEN-LAST:event_btnCrecerUnDiaActionPerformed

    private void btnCrecerNDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrecerNDiasActionPerformed
        // TODO add your handling code here:
        raton1.crecer(Integer.parseInt(txtDias.getText()));
        txtPeso.setText(String.format("%.2f", raton1.getPeso()));
        txtEdad.setText(String.valueOf(raton1.getEdad()));
    }//GEN-LAST:event_btnCrecerNDiasActionPerformed

    private void txtDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionRaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionRaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionRaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionRaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionRaton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrecerNDias;
    private javax.swing.JButton btnCrecerUnDia;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblTasaCrecimiento;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTasaCrecimiento;
    // End of variables declaration//GEN-END:variables
}
